import { ThemeProvider } from '@/components/theme-provider';
import { LenisProvider } from '@/components/lenis-provider';
import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';
import type { Metadata } from 'next';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning className="disable-transitions">
            <head>
                <script
                    dangerouslySetInnerHTML={{
                        __html: `
                            (function() {
                                try {
                                    const theme = localStorage.getItem('theme') || 'dark';
                                    if (theme !== 'dark' && theme !== 'light') {
                                        localStorage.setItem('theme', 'dark');
                                        theme = 'dark';
                                    }
                                const root = document.documentElement;
                                root.classList.add('disable-transitions');
                                if (theme === 'dark') {
                                    root.classList.add('dark');
                                    root.style.colorScheme = 'dark';
                                } else {
                                    root.classList.remove('dark');
                                    root.style.colorScheme = 'light';
                                }
                                } catch (e) {
                                    // Fallback if localStorage is unavailable
                                    document.documentElement.classList.add('dark');
                                    document.documentElement.style.colorScheme = 'dark';
                                }
                            })();
                        `,
                    }}
                />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ThemeProvider defaultTheme="dark">
                    <LenisProvider>{children}</LenisProvider>
                    <Toaster position="bottom-center" />
                    {/* // add 'closeButton' for close button */}
                </ThemeProvider>
            </body>
        </html>
    );
}
